services:
    db:
      image: postgres
      environment:
        POSTGRES_DB: collaborate_app_db
        POSTGRES_USER: collaborate_dengi
        POSTGRES_PASSWORD: bengidengi

    redis:
      image: redis:7 
      ports:
          - "6379:6379"

    backend:
      build: 
        context: .
        dockerfile: Dockerfile.backend
      volumes:
          - .:/usr/src/app
      ports:
          - "8000:8000"
      depends_on:
          - db    # Ensures web service starting when db ready

    frontend:
      build:
        context: .
        dockerfile: Dockerfile.frontend
      volumes:
          - .:/usr/src/app
      ports:
          - "5173:5173"
      depends_on:
          - backend

        

        

    
