# Generated by Django 4.2.7 on 2023-12-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
    ]
