# Generated by Django 4.2.8 on 2023-12-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_user_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='is_accepted',
        ),
    ]
