# Generated by Django 4.2.9 on 2024-01-13 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcalidrawInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elements', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excalidraw_instances', to='service.project')),
            ],
        ),
    ]
