# Generated by Django 4.2.9 on 2024-02-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_excalidrawinstance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcalidrawInstance',
        ),
    ]
