# Generated by Django 4.2.9 on 2024-01-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_excalidrawinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excalidrawinstance',
            name='elements',
            field=models.JSONField(null=True),
        ),
    ]
