# Generated by Django 5.0.2 on 2024-03-02 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_excalidrawinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcalidrawFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mimeType', models.CharField(max_length=100)),
                ('file_id', models.CharField(max_length=100)),
                ('dataURL', models.TextField()),
                ('created', models.IntegerField()),
                ('lastRetrieved', models.IntegerField()),
                ('related_whiteboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard_files', to='service.excalidrawinstance')),
            ],
        ),
    ]
