# Generated by Django 5.0.2 on 2024-03-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_excalidrawfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excalidrawfile',
            name='created',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='excalidrawfile',
            name='lastRetrieved',
            field=models.BigIntegerField(),
        ),
    ]
