# Generated by Django 5.0.3 on 2024-03-18 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_alter_excalidrawfile_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcalidrawFile',
        ),
    ]
