# Generated by Django 5.0.3 on 2024-04-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_delete_excalidrawfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
