# Generated by Django 5.0.4 on 2024-05-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_file_file_type_file_uploaded_by'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room_id'], include=('timestamp',), name='chat_index'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['item'], include=('created_at',), name='comment_index'),
        ),
        migrations.AddIndex(
            model_name='excalidrawinstance',
            index=models.Index(fields=['project'], name='excalidraw_index'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['project'], include=('timestamp',), name='file_index'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['project'], include=('receiver',), name='invitation_index'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['project'], include=('created_at',), name='item_index'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['project'], include=('created_by',), name='note_index'),
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['project'], include=('user', 'is_admin'), name='project_membership_index'),
        ),
    ]
