name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: collaborate_app_db
          POSTGRES_USER: collaborate_dengi
          POSTGRES_PASSWORD: bengidengi
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run tests
      run: |
        python manage.py test
